from fpdf import FPDF
import pandas as pd
from datetime import datetime

# --- Load Data ---
alerts = pd.read_csv("data/final_alerts.csv")
ml = pd.read_csv("data/ml_results.csv")

# --- Stats ---
total_alerts = len(alerts)
critical_count = len(alerts[alerts["severity"] == "CRITICAL"])
medium_count = len(alerts[alerts["severity"] == "MEDIUM"])
anomaly_count = len(ml[ml["ml_label"] == "ANOMALY"])
top_ip = alerts["ip"].value_counts().idxmax()
top_user = alerts["user"].value_counts().idxmax()
top_technique = alerts["mitre_technique"].value_counts().idxmax()
report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# --- PDF Class ---
class IncidentReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(30, 30, 30)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, "  MiniSOC - Incident Report", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"MiniSOC Automated Report | Page {self.page_no()} | Confidential", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(220, 50, 50)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, f"  {title}", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def body_text(self, text):
        self.set_font("Helvetica", "", 11)
        self.multi_cell(0, 8, text)
        self.ln(2)

    def key_value(self, key, value, color=None):
        self.set_font("Helvetica", "B", 11)
        self.cell(70, 8, f"  {key}:", ln=False)
        self.set_font("Helvetica", "", 11)
        if color:
            self.set_text_color(*color)
        self.cell(0, 8, str(value), ln=True)
        self.set_text_color(0, 0, 0)

# --- Build PDF ---
pdf = IncidentReport()
pdf.add_page()

# --- 1. Executive Summary ---
pdf.section_title("1. Executive Summary")
pdf.body_text(
    f"This automated incident report was generated by MiniSOC on {report_time}. "
    f"The system analyzed security logs and detected {total_alerts} alerts using a combination of "
    f"rule-based detection and machine learning anomaly detection (Isolation Forest). "
    f"Immediate attention is required for {critical_count} CRITICAL severity alerts."
)

# --- 2. Key Metrics ---
pdf.section_title("2. Key Metrics")
pdf.key_value("Report Generated", report_time)
pdf.key_value("Total Alerts", total_alerts)
pdf.key_value("Critical Alerts", critical_count, color=(200, 0, 0))
pdf.key_value("Medium Alerts", medium_count, color=(200, 150, 0))
pdf.key_value("ML Anomalies Detected", anomaly_count)
pdf.key_value("Most Targeted User", top_user)
pdf.key_value("Top Attacking IP", top_ip)
pdf.key_value("Primary MITRE Technique", top_technique)

# --- 3. Top 10 Critical Alerts ---
pdf.ln(3)
pdf.section_title("3. Top 10 Critical Alerts")

top_alerts = alerts[alerts["severity"] == "CRITICAL"].head(10)

for i, (_, row) in enumerate(top_alerts.iterrows(), 1):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(0, 7, f"  Alert #{i} - {row['alert_id']}", fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"  Time: {row['timestamp']}   |   User: {row['user']}   |   IP: {row['ip']}   |   Country: {row['country']}", ln=True)
    pdf.cell(0, 6, f"  Reason: {row['reason']}   |   MITRE: {row['mitre_id']} - {row['mitre_technique']}", ln=True)
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 6, f"  Action: {row['recommended_action']}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

# --- 4. MITRE ATT&CK Summary ---
pdf.add_page()
pdf.section_title("4. MITRE ATT&CK Techniques Observed")
mitre_summary = alerts["mitre_technique"].value_counts()
for technique, count in mitre_summary.items():
    pdf.key_value(technique, f"{count} occurrences")

# --- 5. Recommendations ---
pdf.ln(3)
pdf.section_title("5. Recommendations")
recommendations = [
    "1. Immediately block all flagged malicious IPs at the firewall level.",
    "2. Force password reset for all targeted user accounts.",
    "3. Enable Multi-Factor Authentication (MFA) for admin and root accounts.",
    "4. Investigate after-hours login attempts with the respective users.",
    "5. Review and update IP blacklist with newly detected malicious IPs.",
    "6. Conduct a full audit of privileged account activity.",
    "7. Consider deploying honeypot accounts to detect credential stuffing.",
]
for rec in recommendations:
    pdf.body_text(rec)

# --- 6. ML Detection Summary ---
pdf.ln(3)
pdf.section_title("6. ML Anomaly Detection Summary")
pdf.body_text(
    f"The Isolation Forest model analyzed {len(ml)} log entries and flagged "
    f"{anomaly_count} as anomalous ({(anomaly_count/len(ml)*100):.1f}% anomaly rate). "
    f"ML detection identified suspicious patterns in normal-looking login events "
    f"that rule-based detection alone would have missed."
)

avg_risk = ml.groupby("event_type")["risk_score"].mean().round(2)
for event, score in avg_risk.items():
    pdf.key_value(f"Avg Risk Score - {event}", f"{score}/100")

# --- Save ---
output_path = "reports/incident_report.pdf"
pdf.output(output_path)
print(f" Incident Report generated → {output_path}")